### ISSUE TITLE
null affectation on not-source Simples_Document

### ISSUE THREAD

**Issue by mattjmattj** [v-technologies/simpl-es#16]
When working with a Simples_Document configured with the `source` option set to `false`, setting `null` as the value of a property causes the whole document data to be set to the name of the property.

Example below:
```php
$document = new Simples_Document();
$document->foo = null;
$data = $document->get();
// $data === "foo"
```

The bug is caused by the `set` method of Simples_Document : 

```php
public function set($name, $data = null) {
	if (isset($data)) {
		$this->_data[$name] = $this->_import($data) ;
	} else {
		$data = $name ; // <<--- THE DATA IS SET TO THE PROPERTY NAME HERE
		$source = $this->config('source') ;
		if ($source === true || ($source === null && (isset($data['_source']) || isset($data['fields'])))) {
			// [...]
		} else {
			$this->_data = $this->_import($data) ; // <<--- AND REPLACED HERE
		}
	}

	return $this ;
}
```

**Comment by RomainS** [comment]
:+1: 
Maybe you could suggest a PR that suppress this strange behavior, (if not used anywhere) ?

**Comment by mattjmattj** [comment]
The big thing here is that the `set` function has multiple responsibilities :hankey: since it is used both to set one specific property and to set the whole data at once. The semantic of its arguments is different in each case. It's a design issue, actually.

Without rewriting everything, it might be interesting to address the issue in the `__set` method, which is currently just a proxy to `set`. Maybe should `__set` do : 

```php
public function __set($name, $value) {
	if (!is_null($value)) {
		$this->set($name, $value) ;
	}
}
```

**Comment by RomainS** [comment]
:+1: :+1:

**Comment by scharrier** [comment]
I am _SO_ sorry for that, guys. ❤️
